# Adapted from Relude's .travis.yml file.
# https://github.com/kowainik/relude/blob/master/.travis.yml

sudo: true
language: haskell

git:
  depth: 5

cache:
  directories:
  - "$HOME/.cabal"
  - "$HOME/.ghc"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

matrix:
  include:

  - ghc: 8.6.1
    env: GHCVER='8.6.1' CABALVER='2.4'
    os: linux
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-8.6.1
        - cabal-install-2.4

  - ghc: 8.4.3
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml"
    os: linux
    addons:
      apt:
        packages:
        - libgmp-dev

install:
  - |
    set -e
    if [ -z "$STACK_YAML" ]; then
      mkdir -p ~/.local/bin
      export PATH="/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.local/bin:$PATH"
      echo $PATH
      cabal v2-update
      cabal v2-install tasty-discover --symlink-bindir="$HOME/.local/bin"
      cabal v2-build --enable-tests --enable-benchmarks
    else
      echo "$TRAVIS_BUILD_DIR"
      mkdir -p ~/.local/bin
      export PATH="$HOME/.local/bin:$PATH"
      travis_retry curl -L 'https://www.stackage.org/stack/linux-x86_64' | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
      stack --version
      stack setup --no-terminal
      stack ghc -- --version
      stack build --only-dependencies --no-terminal
      stack install hlint
    fi
script:
  - |
    if [ -z "$STACK_YAML" ]; then
      cabal v2-test
      cabal v2-haddock
    else
      stack build --test --bench --no-run-benchmarks --no-terminal
      hlint .
    fi
notifications:
email: false
