name:                ozil
version:             0.0.1.0
github:              "theindigamer/ozil"
license:             BSD3
author:              "Varun Gandhi"
maintainer:          "theindigamer15@gmail.com"
copyright:           "2018 Varun Gandhi"

extra-source-files:
- Readme.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/theindigamer/ozil#readme>

dependencies:
- base >= 4.11 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Wnoncanonical-monad-instances
- -Wnoncanonical-monadfail-instances
- -Wnoncanonical-monoid-instances
- -Wredundant-constraints
- -Wno-type-defaults
- -funbox-strict-fields

default-extensions:
- DeriveGeneric
- DeriveDataTypeable
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- StandaloneDeriving
- FlexibleInstances
- FlexibleContexts
- MultiParamTypeClasses
- BangPatterns
- LambdaCase
- NamedFieldPuns
- OverloadedStrings
- TupleSections
- PatternSynonyms

library:
  source-dirs: src
  dependencies:
  - optparse-applicative >= 0.14 && < 0.15
  - yaml >= 0.8.32 && < 0.11
  - aeson >= 1.3 && < 1.5
  - bytestring >= 0.10.8.2 && < 0.11
  - text >= 1.2 && < 1.3
  - containers >= 0.5.10 && < 0.7
  - vector >= 0.12 && < 0.13
  - lens >= 4.16 && < 4.18
  - mtl >= 2.2.2 && < 2.3
  - directory >= 1.3 && < 1.4
  - filepath >= 1.4 && < 1.5
  - fsnotify >= 0.2.1.1 && < 0.4
  - megaparsec >= 6.5 && < 7.1
  - process
  - brick >= 0.37 && < 0.40
  - vty >= 5.21 && < 5.24
  - word-wrap >= 0.4 && < 0.5

executables:
  ozil:
    main:                ozil.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ozil

tests:
  ozil-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ozil
